### PR TITLE
Add compatibility with RetroArch (aarch64) for Android OS (Closes #60)

### LINKED ISSUE #60: Allow compatibility with aarch64
The aarch64 builds of RetroArch have an app id of com.retroarch.aarch64, so IAGL can't find it! Is there any way we could have either a toggle or an automatic detection of which we have installed?

### PR DESCRIPTION
**Pull request by drinfernoo**
This could probably use a bit more testing, but it works perfectly on my OnePlus 6T and Nvidia Shield 👍 Let me know if I missed anything or need to fix anything up.

### CODE REVIEW

**Comment by Clutz450** [comment]
How do I help you test this?  Is there a new apk you made I can download so I can try it out?  I'm still very new to github. Thanks.

**Comment by drinfernoo** [comment]
If you download the `aarch64` branch from my repo and install it from zip, you should be able to test against the official RetroArch aarch64 builds.

**Comment by zach-morris** [comment]
Unfortunately I don't have an aarch64 box to test it with, so I'm just going to pull it.  I will have to do this piecemeal though, since some things, like the external launch command database I automatically generate with a script on my end, to keep up with any core additions/changes from Retroarch.

**Comment by drinfernoo** [comment]
That's fair, let me know if I can help with anything else 👍

**Comment by zach-morris** [comment]
I believe this is pulled piecemeal now, with some slight changes:
There was an error in the code for config file searching, which I think is resolved now
I removed the stop command for android and added the stop flag argument to the launch command

**Pull request closed without merging**
