### PR TITLE
Updated remix launch

### PR DESCRIPTION
**Pull request by camatthew**
Added support for retroelec

### CODE REVIEW

**Comment by zach-morris** [comment]
Thanks!
This might get confusing, as it seems there are a few forks of the remix version of LE now.  I see:
[LE 9.x RR](https://forum.libreelec.tv/thread/12662-libreelec-9-x-rr-emulationstation-retroarch-pegasus-dolphinqt-moonlight-chrome-s/?pageNo=1) (5schatten) - seems to still use [retroarch.start](https://github.com/5schatten/LibreELEC-RR/blob/libreelec-9.x-rr/packages/5schatten/emulation-frontends/retroarch/scripts/Generic/retroarch.start)

[RetroELEC](https://forum.libreelec.tv/thread/302-retroelec-generic-rpi-xu4-emulationstation-retroarch-kodi/?pageNo=1) (escalade) - seems to use [retroarch.sh
](https://github.com/escalade/RetroELEC/tree/le9/packages/escalade/libretro/retroarch/scripts)

Perhaps it makes sense to list both separately?  Or is one actively being maintained and the other abandoned?

**Comment by camatthew** [comment]
Probably its best to combine them to prevent clutter from more systems

**Comment by zach-morris** [comment]
Yeah, I think your right.  Maybe just an if statement in remix_launch.sh to see which file exists and then launch the correct one?  I'll think about it.

**Comment by camatthew** [comment]
That sounds right

**Pull request closed without merging**
