### PR TITLE
[python] update xbmc.translatePath() to xbmcvfs

### PR DESCRIPTION
**Pull request by rudi-beer**
As per Alpha2 of Matrix. The correct syntax for xbmc.translatePath() is xbmcvfs.translatePath()

### CODE REVIEW

**Comment by heitbaum** [comment]
Hi @zach-morris  - I note that the v19 branch did not have this in it. What is the plan for bringing the v19 branch up to 2.1.7 / bringing v19 across to main? I note some other issues with the addon.xml files needing to be uplifted to python 3.0.0 (or the update to enable 2.x / 3.x / removal of python requires from these files.)

**Comment by zach-morris** [comment]
I decided to go and rewrite a good portion of the addon with the major change to py3.  I'll push the current state of it soon to that branch and make it main (hopefully) more or less in line with v19 release, which is still in alpha.

**Comment by heitbaum** [comment]
Sounds good. I have been running Matrix most of the year, and am updating to git master a couple times a week and compiling and running Matrix as our Main Kodi system, so happy to do testing of your up coming releases.

**Comment by zach-morris** [comment]
Updated in v19, will release soon

**Pull request closed without merging**
